use context url-file("https://raw.githubusercontent.com/neu-pdi/cs2000-public-resources/refs/heads/main/static/","cs2000.arr")
square(40, "solid", "blue")
sq-blue = square(100, "solid", "blue")
overlay(sq-blue, sq-blue)
rectangle(300, 200, "solid", "black")
rec-black = rectangle(300, 200, "solid", "black")
circle(30, "solid", "yellow")
yellow-circle = circle(30, "solid", "yellow")
overlay(yellow-circle, rec-black)
triangle(70, "solid", "purple")
orange-tri = triangle(70, "solid", "purple")
purple-tri = triangle(70, "solid", "purple")
square(50, "solid", "red")
sq-red = square(50, "solid", "red")
sq-red2 = rotate(45, sq-red)
sq-red3 = rotate(90, sq-red) 
sq-red4 = rotate(180, sq-red)
octagon1 = overlay(sq-red, sq-red2)
overlay((text("stop", 35, "white")), octagon1) 
side-length = 80 
square(80, "solid", "pink")
rec-2x = above(sq-blue, sq-blue)
rec-2x
above(yellow-circle, rec-2x)
above(beside(yellow-circle, yellow-circle), rec-2x)
rec3 = rotate(90, rec-2x)
star1 = star(10, "solid", "white")
star2 = beside(star1, star1)
beside(star2, star2)
star4 = beside(star2, star2)
star8 = above(star4, star4) 
star16 = above(star8, star8)
overlay(star16, rec3)
overlay-align("left", "top", star16, rec3)
circ1 = circle(100, "solid", "red")
circ2 = circle(80, "solid", "white")
circ3 = circle(60, "solid", "red")
circ4 = overlay(circ2, circ1)
overlay(circ3, circ4)